Sgu.StudentTesting/Sgu.StudentTesting.PL/Controllers/TestController.cs
using AutoMapper;
using Common;
using Sgu.StudentTesting.BLL.Contracts;
using Sgu.StudentTesting.PL.ViewModel.Question;
using Sgu.StudentTesting.PL.ViewModel.Test;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sgu.StudentTesting.PL.Controllers
{
    public class TestController : Controller
    {
        private readonly ITestLogic _testLogic;


        public TestController(ITestLogic testLogic)
        {
            _testLogic = testLogic;
        }

        #region General

        // GET: Test
        public ActionResult Index(int id)
        {
            //Берем студента
            var a = Mapper.Map<IEnumerable<Test>, IEnumerable<TestVM>>(this._testLogic.GetTestsStudent(id));
            ViewData["idUser"] = id;
            return this.View(a);
        }
        
        public ActionResult SaveTest(TestVM test) //Принимает пройденный тест
        {
            try
            {
                if (ModelState.IsValid)
                {
                    this._testLogic.AddTest(Mapper.Map<TestVM, Test>(test));
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex);
            }
            return View(test);
        }
        [HttpGet]
        public ActionResult StartTest(int id,int idSubject)
        {
            _testLogic.Initialization(idSubject);
            ViewData["idUser"] = id;
            return View(Mapper.Map<Question, QuestionDisplayVM>(_testLogic.NewQuestion()));
        }
        [HttpPost]
        public ActionResult StartTest(int answer)
        {
            if (_testLogic.NewQuestion() == null)
            {
                return View("Result", new { result = 4});
            }
            return View();
        }           
            
        public RedirectToRouteResult BackToStudents()
        {
            return RedirectToAction("Index","User");
        }
        public RedirectToRouteResult BackToSubject(int id)
        {
            return RedirectToAction("Index","Subject",new { id = id });
        }
        public ActionResult ListAnswers(int idTest, int idUser)
        {
            var a = Mapper.Map<IEnumerable<QuestionInTest>, IEnumerable<QuestionInTestDisplayVM>>(_testLogic.GetQuestionInTestBySubject(idTest));

            ViewData["idUser"]=idUser;
            return View(a);
        }
        public ActionResult Result(int result)
        {
            return View(result);
        }
        #endregion[/Method]
    }
}

Sgu.StudentTesting/Sgu.StudentTesting.PL/Views/Test/Index.cshtml
@model IEnumerable<Sgu.StudentTesting.PL.ViewModel.Test.TestVM>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body style="font-size:20px">
    <table class="table">
        <tr>
            <th>
                Название предмета
            </th>
            <th>
                Дата прохождения
            </th>
            <th>
                Результат
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameSubject)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                @Html.ActionLink("Вопросы","ListAnswers", new { idTest = item.IdTest, idUser=(int)ViewData["idUser"]})
            </td>
         </tr>
    }    
    </table>
    <div>
        @Html.ActionLink("Вернуться", "Index","Home")
    </div>
</body>
</html>

Sgu.StudentTesting/Sgu.StudentTesting.PL/Views/Test/ListAnswers.cshtml
@model IEnumerable<Sgu.StudentTesting.PL.ViewModel.Question.QuestionInTestDisplayVM>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListAnswers</title>
</head>
<body style="font-size:20px">
    <table class="table">
        <tr>
            <th>
                Вопрос
            </th>
            <th>
                Вариант 1
            </th>
            <th>
                Вариант 2
            </th>
            <th>
                Вариант 3
            </th>
            <th>
                Вариант 4
            </th>
            <th>
                Ответ
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VariantOfAnswer1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VariantOfAnswer2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VariantOfAnswer3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VariantOfAnswer4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer)
            </td>
        </tr>
    }    
    </table>
    <div>
        @Html.ActionLink("Вернуться","Index", new { id = (int)ViewData["idUser"]})
    </div>
</body>
</html>

Sgu.StudentTesting/Sgu.StudentTesting.PL/Views/Test/Result.cshtml
@model int

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Result</title>
</head>
<body style = "margin:20% 40%; font-size:40px" >
    <div> 
        Результат
    </div>
    <div>
        Model
    </div>
</body>
</html>

Sgu.StudentTesting/Sgu.StudentTesting.PL/Views/Test/StartTest.cshtml
@model Sgu.StudentTesting.PL.ViewModel.Question.QuestionDisplayVM


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NextQuestion</title>
</head>
<body style="margin-top:50%">

    <div> 

       @using (Html.BeginForm("NextQuestion", "Test",FormMethod.Post))
       {
            <p><b>@Html.DisplayFor(modelItem => Model.Text)</b></p>
            <p><input name="answer" type="radio" value="1"> @Html.DisplayFor(modelItem => Model.VariantOfAnswer1)</p>
            <p><input name="answer" type="radio" value="2">@Html.DisplayFor(modelItem => Model.VariantOfAnswer2)</p>
            <p><input name="answer" type="radio" value="3" checked> @Html.DisplayFor(modelItem => Model.VariantOfAnswer3)</p>
            <p><input name="answer" type="radio" value="4" checked> @Html.DisplayFor(modelItem => Model.VariantOfAnswer4)</p>
            <p><input type="submit" value="Выбрать"></p>
       }
    </div>
</body>
</html>